Build system updates.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp-misc/trunk/subnetcalc@1648 acdd8558-d4fd-0310-b0a5-8cf3c1ec824a

diff --git a/build-deb b/build-deb
--- a/build-deb
+++ b/build-deb
@@ -1,8 +1,8 @@
-#!/bin/bash
+#!/bin/bash -e
 # $Id$
 #
 # Debian Packaging Scripts
-# Copyright (C) 2002-2012 by Thomas Dreibholz
+# Copyright (C) 2002-2013 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -19,27 +19,96 @@
 #
 # Contact: dreibh@iem.uni-due.de
 
+if [ ! -e ./debian.conf ] ; then
+   echo >&2 "ERROR: debian.conf does not exist -> no configuration for the new package!"
+   exit 1
+fi
 . ./debian.conf
+
+OVERRIDE_PACKAGE_DISTRIBUTION="$1"
 
 
 CHANGELOG_HEADER="`head -n1 debian/changelog`"
 
+# The package name, e.g. MyApplication
 PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
-PACKAGE_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-Z0-9 ]*(//" -e "s/).*//" -e "s/ //g" -e "s/^[0-9]*://"`
-INPUT_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`
+# The package distribution, e.g. precise, raring, ...
+PACKAGE_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`
+# The package's version, e.g. 1.2.3-1ubuntu1
+PACKAGE_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g"`
+# The package's output version, e.g. 1.2.3-1ubuntu
+OUTPUT_VERSION=`echo $PACKAGE_VERSION   | sed -e "s/\(ubuntu\)[0-9]*$/\1/"`
+# The package's Debian version, e.g. 1.2.3-1
+DEBIAN_VERSION=`echo $OUTPUT_VERSION    | sed -e "s/ubuntu$//1"`
+# The package's upstream version, e.g. 1.2.3
+UPSTREAM_VERSION=`echo $DEBIAN_VERSION  | sed -e "s/-[0-9]*$//"`
+# The package's plain upstream version, e.g. 1.2.3 (without e.g. ~svn<xxxx>)
+PLAIN_VERSION=`echo $UPSTREAM_VERSION   | sed -e "s/\([0-9\.]*\)[-+~].*$/\1/"`
 
 
-echo "######################################################################"
-echo "CHANGELOG_HEADER:   $CHANGELOG_HEADER"
-echo "PACKAGE:            $PACKAGE"
-echo "INPUT_DISTRIBUTION: $INPUT_DISTRIBUTION"
-echo "######################################################################"
+echo -e "\x1b[34m######################################################################\x1b[0m"
+echo -e "\x1b[34mCHANGELOG_HEADER:     $CHANGELOG_HEADER\x1b[0m"
+echo -e "\x1b[34mPACKAGE:              $PACKAGE\x1b[0m"
+echo -e "\x1b[34mPACKAGE_DISTRIBUTION: $PACKAGE_DISTRIBUTION\x1b[0m"
+echo -e "\x1b[34mPACKAGE_VERSION       $PACKAGE_VERSION\x1b[0m"
+echo -e "\x1b[34mOUTPUT_VERSION:       $OUTPUT_VERSION\x1b[0m"
+echo -e "\x1b[34mDEBIAN_VERSION:       $DEBIAN_VERSION\x1b[0m"
+echo -e "\x1b[34mUPSTREAM_VERSION:     $UPSTREAM_VERSION\x1b[0m"
+echo -e "\x1b[34mPLAIN_VERSION:        $PLAIN_VERSION\x1b[0m"
+echo -e "\x1b[34m######################################################################\x1b[0m"
+
+
+if [ "$OVERRIDE_PACKAGE_DISTRIBUTION" != "" ] ; then
+   PACKAGE_DISTRIBUTION="$OVERRIDE_PACKAGE_DISTRIBUTION"
+   echo ""
+   echo -e "\x1b[34m**** Overriding PACKAGE_DISTRIBUTION: PACKAGE_DISTRIBUTION=${PACKAGE_DISTRIBUTION}! ****\x1b[0m"
+   echo ""
+fi
+
+
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Generating source package ======================================\x1b[0m"
+echo -e ""
 
 sudo echo ""
+./clean-deb
+./make-deb ${PACKAGE_DISTRIBUTION}
 
-./clean-deb && \
-./make-deb ${INPUT_DISTRIBUTION} && \
-DSC_FILE=${PACKAGE}_${PACKAGE_VERSION}~${INPUT_DISTRIBUTION}1~ppa0.dsc && \
-sudo pbuilder build $DSC_FILE && \
-CHANGES_FILE=/var/cache/pbuilder/result/${PACKAGE}_${PACKAGE_VERSION}~${INPUT_DISTRIBUTION}1~ppa0_*.changes && \
-lintian -iIEv --pedantic $CHANGES_FILE
+if [ "$PACKAGE_DISTRIBUTION" = "unstable" -o \
+     "$PACKAGE_DISTRIBUTION" = "testing"  -o \
+     "$PACKAGE_DISTRIBUTION" = "stable"   -o \
+     "$PACKAGE_DISTRIBUTION" = "default" ] ; then
+   if [ "$PACKAGE_DISTRIBUTION" = "default" ] ; then
+      version=${PACKAGE_VERSION}
+   else
+      version=${DEBIAN_VERSION}
+   fi
+   changesFilesPattern="${PACKAGE}_${version}_*.changes"
+   dscFile=`ls ${PACKAGE}_${version}.dsc | tail -n1`
+else
+   changesFilesPattern="${PACKAGE}_${PACKAGE_VERSION}~${PACKAGE_DISTRIBUTION}[0-9]~ppa[0-9]_*.changes"
+   dscFile=`ls ${PACKAGE}_${PACKAGE_VERSION}~${PACKAGE_DISTRIBUTION}[0-9]~ppa[0-9].dsc | tail -n1`
+fi
+
+
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Building source package ========================================\x1b[0m"
+echo -e ""
+
+if [ ! -e "$dscFile" ] ; then
+    echo >&2 "ERROR: Unable to find description file $dscFile!"
+    exit 1
+fi
+sudo pbuilder build $dscFile
+
+
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Running lintian ================================================\x1b[0m"
+echo -e ""
+
+changesFile=`find /var/cache/pbuilder/result/ -name "${changesFilesPattern}"`
+if [ ! -e "$changesFile" ] ; then
+    echo >&2 "ERROR: Unable to find changes file $changesFile!"
+    exit 1
+fi
+lintian -iIEv --pedantic $changesFilesPattern
diff --git a/make-deb b/make-deb
--- a/make-deb
+++ b/make-deb
@@ -1,8 +1,8 @@
-#!/bin/bash
+#!/bin/bash -e
 # $Id$
 #
 # Debian Packaging Scripts
-# Copyright (C) 2002-2012 by Thomas Dreibholz
+# Copyright (C) 2002-2013 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -19,8 +19,6 @@
 #
 # Contact: dreibh@iem.uni-due.de
 
-. ./debian.conf
-
 
 # ---------------------------------------------------------------------------
 # USAGE:
@@ -35,8 +33,8 @@
 DISTRIBUTIONS=`\
 ( \
 while [ x$1 != "x" ] ; do \
-   echo $1 && \
-   shift ; \
+   echo $1 
+   shift
 done \
 ) | sort -u`
 if [ "$DISTRIBUTIONS" == "" ] ; then
@@ -46,68 +44,104 @@ fi
 
 CHANGELOG_HEADER="`head -n1 debian/changelog`"
 
+# The package name, e.g. MyApplication
 PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
-PACKAGE_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-Z0-9 ]*(//" -e "s/).*//" -e "s/ //g" -e "s/^[0-9]*://"`
-INPUT_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`
-UPSTREAM_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-Z0-9 ]*(//" -e "s/).*//" -e "s/[0-9]*$//" -e "s/ //g" -e "s/^[0-9]*://" -e "s/-[^ ]*$//g"`
-OUTPUT_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-Z0-9 ]*(//" -e "s/).*//" -e "s/[0-9]*$//" -e "s/ //g" -e "s/^[0-9]*://"`
-DEBIAN_VERSION=`echo $PACKAGE_VERSION | sed -e "s/ubuntu[0-9]//1"`
+
+# The package distribution, e.g. precise, raring, ...
+PACKAGE_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`
+# The package's version, e.g. 1.2.3-1ubuntu1
+PACKAGE_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g"`
+# The package's output version, e.g. 1.2.3-1ubuntu
+OUTPUT_VERSION=`echo $PACKAGE_VERSION   | sed -e "s/\(ubuntu\)[0-9]*$/\1/"`
+# The package's Debian version, e.g. 1.2.3-1
+DEBIAN_VERSION=`echo $OUTPUT_VERSION    | sed -e "s/ubuntu$//1"`
+# The package's upstream version, e.g. 1.2.3
+UPSTREAM_VERSION=`echo $DEBIAN_VERSION  | sed -e "s/-[0-9]*$//"`
+# The package's plain upstream version, e.g. 1.2.3 (without e.g. ~svn<xxxx>)
+PLAIN_VERSION=`echo $UPSTREAM_VERSION   | sed -e "s/\([0-9\.]*\)[-+~].*$/\1/"`
 
 
-echo "######################################################################"
-echo "CHANGELOG_HEADER:   $CHANGELOG_HEADER"
-echo "PACKAGE:            $PACKAGE"
-echo "INPUT_DISTRIBUTION: $INPUT_DISTRIBUTION"
-echo "UPSTREAM_VERSION:   $UPSTREAM_VERSION"
-echo "PACKAGE_VERSION     $PACKAGE_VERSION"
-echo "OUTPUT_VERSION:     $OUTPUT_VERSION"
-echo "DEBIAN_VERSION:     $DEBIAN_VERSION"
-echo "######################################################################"
+echo -e "\x1b[34m######################################################################\x1b[0m"
+echo -e "\x1b[34mCHANGELOG_HEADER:     $CHANGELOG_HEADER\x1b[0m"
+echo -e "\x1b[34mPACKAGE:              $PACKAGE\x1b[0m"
+echo -e "\x1b[34mPACKAGE_DISTRIBUTION: $PACKAGE_DISTRIBUTION\x1b[0m"
+echo -e "\x1b[34mPACKAGE_VERSION       $PACKAGE_VERSION\x1b[0m"
+echo -e "\x1b[34mOUTPUT_VERSION:       $OUTPUT_VERSION\x1b[0m"
+echo -e "\x1b[34mDEBIAN_VERSION:       $DEBIAN_VERSION\x1b[0m"
+echo -e "\x1b[34mUPSTREAM_VERSION:     $UPSTREAM_VERSION\x1b[0m"
+echo -e "\x1b[34mPLAIN_VERSION:        $PLAIN_VERSION\x1b[0m"
+echo -e "\x1b[34m######################################################################\x1b[0m"
+
+if [ ! -e ./debian.conf ] ; then
+   echo >&2 "ERROR: debian.conf does not exist -> no configuration for the new package!"
+   exit 1
+fi
+. ./debian.conf
 
 
-echo ""
-echo "====== Calling wrap-and-sort =========================================="
-echo ""
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Calling wrap-and-sort ==========================================\x1b[0m"
+echo -e ""
 wrap-and-sort -a -v || exit 1
 
 
-echo ""
-echo "====== Creating upstream package ======================================"
-echo ""
-UPSTREAM_PACKAGE="`find . -name $PACKAGE-$UPSTREAM_VERSION.tar.gz`"
-if [ "$UPSTREAM_PACKAGE" == "" ]; then
-   rm -f $PACKAGE-*.gz $PACKAGE"_"*.gz
-   echo Running "$MAKE_DIST" ...
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating upstream package ======================================\x1b[0m"
+echo -e ""
+UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "$PACKAGE-*.gz" -printf '%f'`"
+UPSTREAM_PACKAGE_TYPE="gz"
+if [ ! -e "$UPSTREAM_PACKAGE" ] ; then
+   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "$PACKAGE-*.bz2" -printf '%f'`"
+   UPSTREAM_PACKAGE_TYPE="bz2"
+fi
+if [ ! -e "$UPSTREAM_PACKAGE" ]; then
+   rm -f $PACKAGE-*.gz $PACKAGE"_"*.gz $PACKAGE-*.bz2 $PACKAGE"_"*.bz2
+   echo -e "\x1b[34m------ Running MAKE_DIST ... ------\x1b[0m"
+   echo "\$ $MAKE_DIST"
    eval "$MAKE_DIST"
-   UPSTREAM_PACKAGE="`find . -name $PACKAGE-*.gz`"
-   echo ""
-   echo "==> Upstream package is $UPSTREAM_PACKAGE"
-   echo ""
-   if [ ! -e $UPSTREAM_PACKAGE ] ; then
-      echo "ERROR: No upstrem package found!"
+
+   echo -e "\x1b[34m------ Looking for upstream package ... ------\x1b[0m"
+   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name $PACKAGE-*.gz -printf '%f'`"
+   UPSTREAM_PACKAGE_TYPE="gz"
+   if [ ! -e "$UPSTREAM_PACKAGE" ] ; then
+      UPSTREAM_PACKAGE="`find . -maxdepth 1 -name $PACKAGE-*.bz2 -printf '%f'`"
+      UPSTREAM_PACKAGE_TYPE="bz2"
+   fi
+   if [ ! -e "$UPSTREAM_PACKAGE" ] ; then
+      echo -e "\x1b[34mERROR: No upstrem package found!\x1b[0m"
       exit 1
    fi
 fi
+echo -e ""
+echo -e "\x1b[34m==> Upstream package is $UPSTREAM_PACKAGE (type is $UPSTREAM_PACKAGE_TYPE)\x1b[0m"
+echo -e ""
 
 
-echo ""
-echo "====== Creating packages =============================================="
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating packages ==============================================\x1b[0m"
 for DISTRIBUTION in $DISTRIBUTIONS ; do
 
-   echo ""
-   echo "------ Creating package for $DISTRIBUTION ------"
+   echo -e ""
+   echo -e "\x1b[34m------ Creating package for $DISTRIBUTION ------\x1b[0m"
 
    success=1
-   cp ${UPSTREAM_PACKAGE} ${PACKAGE}_${UPSTREAM_VERSION}.orig.tar.gz && \
-   cp ${UPSTREAM_PACKAGE} ${PACKAGE}_$OUTPUT_VERSION.orig.tar.gz && \
-   cp ${UPSTREAM_PACKAGE} ${PACKAGE}_$DEBIAN_VERSION.orig.tar.gz && \
-   rm -rf ${PACKAGE}-${UPSTREAM_VERSION} && \
-   rm -rf ${PACKAGE}-${UPSTREAM_VERSION}.orig && \
-   tar xzf ${UPSTREAM_PACKAGE} && \
-   cp -r ${PACKAGE}-${UPSTREAM_VERSION} ${PACKAGE}-${UPSTREAM_VERSION}.orig && \
-   cp -r debian ${PACKAGE}-${UPSTREAM_VERSION} && \
-   find ${PACKAGE}-${UPSTREAM_VERSION} -name .svn | xargs --no-run-if-empty rm -rf && \
-   cd ${PACKAGE}-${UPSTREAM_VERSION} && \
+   cp ${UPSTREAM_PACKAGE} ${PACKAGE}_${UPSTREAM_VERSION}.orig.tar.$UPSTREAM_PACKAGE_TYPE 
+   cp ${UPSTREAM_PACKAGE} ${PACKAGE}_$OUTPUT_VERSION.orig.tar.$UPSTREAM_PACKAGE_TYPE 
+   cp ${UPSTREAM_PACKAGE} ${PACKAGE}_$DEBIAN_VERSION.orig.tar.$UPSTREAM_PACKAGE_TYPE 
+   rm -rf ${PACKAGE}-${UPSTREAM_VERSION} 
+   rm -rf ${PACKAGE}-${UPSTREAM_VERSION}.orig 
+   if [ "$UPSTREAM_PACKAGE_TYPE" = "gz" ] ; then
+      tar xzf ${UPSTREAM_PACKAGE}
+   elif [ "$UPSTREAM_PACKAGE_TYPE" = "bz2" ] ; then
+      tar xjf ${UPSTREAM_PACKAGE}
+   else
+      echo 2>&1 "ERROR: Bad archive format: $UPSTREAM_PACKAGE"
+      exit 1
+   fi 
+   cp -r ${PACKAGE}-${UPSTREAM_VERSION} ${PACKAGE}-${UPSTREAM_VERSION}.orig 
+   cp -r debian ${PACKAGE}-${UPSTREAM_VERSION} 
+   find ${PACKAGE}-${UPSTREAM_VERSION} -name .svn | xargs --no-run-if-empty rm -rf 
+   cd ${PACKAGE}-${UPSTREAM_VERSION} 
    success=0
 
    if [ $success -ne 0 ] ; then
@@ -117,7 +151,7 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
    if [ "$DISTRIBUTION" != "default" ] ; then
       if [ "$DISTRIBUTION" = "unstable" -o "$DISTRIBUTION" = "testing" -o "$DISTRIBUTION" = "stable" ] ; then
          # Debian: Also remove Launchpad Bug IDs.
-         sed -e "s/$INPUT_DISTRIBUTION;/$DISTRIBUTION;/1" \
+         sed -e "s/$PACKAGE_DISTRIBUTION;/$DISTRIBUTION;/1" \
              -e "s/ubuntu[0-9]//1" \
              -e "/(LP: #/D" \
              <debian/changelog | ../filter-empty-entries "$DEBIAN_LAST_ENTRY" >debian/changelog.new
@@ -125,7 +159,7 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
          # Ubuntu PPA
          # Naming example: 2.7.7-0ubuntu1~natty1~ppa0
          # Ubuntu: Also remove Debian Bug IDs.
-         sed -e "s/$INPUT_DISTRIBUTION;/$DISTRIBUTION;/1" \
+         sed -e "s/$PACKAGE_DISTRIBUTION;/$DISTRIBUTION;/1" \
              -e "s/$PACKAGE_VERSION/$PACKAGE_VERSION~${DISTRIBUTION}1~ppa0/1" \
              -e "/(Closes: #/D" \
              <debian/changelog | ../filter-empty-entries "$UBUNTU_LAST_ENTRY" >debian/changelog.new
@@ -164,8 +198,8 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
       mv debian/control.new debian/control
    fi
 
-   echo ""
-   echo "------ Creating diff file $PACKAGE-$PACKAGE_VERSION.diff.gz ------"
+   echo -e ""
+   echo -e "\x1b[34m------ Creating diff file $PACKAGE-$PACKAGE_VERSION.diff.gz ------\x1b[0m"
    (
       cd ..
       diff -urN "--exclude=*~" "--exclude=.svn" "--exclude=.git" \
@@ -174,8 +208,8 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
    )
 
 
-   echo ""
-   echo "------ Building source package ------"
+   echo -e ""
+   echo -e "\x1b[34m------ Building source package ------\x1b[0m"
 
    # Without signature:
    # debuild -us -uc
@@ -186,7 +220,10 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
    # Use -i to ignore .svn files!
 
 
-   if [ "$SKIP_PACKAGE_SIGNING" != "" -a $SKIP_PACKAGE_SIGNING -eq 1 ] ; then
+   if [ "$SKIP_PACKAGE_SIGNING" = "" ] ; then
+      SKIP_PACKAGE_SIGNING=0 
+   fi
+   if [ $SKIP_PACKAGE_SIGNING -eq 1 ] ; then
       # Build source package without signature:
       debuild -us -uc -S "-k$MAINTAINER" -i || exit 1
    else
@@ -214,7 +251,7 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
       dscFile=`ls ${PACKAGE}_${PACKAGE_VERSION}~${DISTRIBUTION}[0-9]~ppa[0-9].dsc | tail -n1`
    fi
    if [ ! -e $dscFile ] ; then
-      echo "ERROR: $dscFile has not been generated successfully -> Aborting!"
+      echo -e "\x1b[34mERROR: $dscFile has not been generated successfully -> Aborting!\x1b[0m"
       exit 1
    fi
 
@@ -226,20 +263,20 @@ if [ -e "$UPSTREAM_PACKAGE.asc" ] ; then
    rm -f "$UPSTREAM_PACKAGE.asc"
 fi
 if [ "$SKIP_PACKAGE_SIGNING" != "" -a ! $SKIP_PACKAGE_SIGNING -eq 1 ] ; then
-   echo ""
-   echo "====== Sign upstream package =========================================="
-   echo ""
-   echo "Signing upstream package $UPSTREAM_PACKAGE ..."
+   echo -e ""
+   echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Sign upstream package ==========================================\x1b[0m"
+   echo -e ""
+   echo -e "\x1b[34mSigning upstream package $UPSTREAM_PACKAGE ...\x1b[0m"
    gpg -sab "$UPSTREAM_PACKAGE"
 fi
 
 
 
-echo ""
-echo "====== Command overview ==============================================="
-echo ""
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Command overview ===============================================\x1b[0m"
+echo -e ""
 
-echo "Upload to PPA:"
+echo -e "\x1b[34mUpload to PPA:\x1b[0m"
 for DISTRIBUTION in $DISTRIBUTIONS ; do
    if [ "$DISTRIBUTION" = "unstable" -o \
         "$DISTRIBUTION" = "testing"  -o \
@@ -257,20 +294,20 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
       ppa="ppa"
       changesFile=`ls ${PACKAGE}_${PACKAGE_VERSION}~${DISTRIBUTION}[0-9]~ppa[0-9]_source.changes | tail -n1`
    fi
-   echo "   dput $ppa $changesFile"
+   echo -e "\x1b[34m   dput $ppa $changesFile\x1b[0m"
 done
-echo ""
+echo -e ""
 
 
 
 if [ -e make-symbols ] ; then
-   echo "################################################################"
-   echo "Do not forget to run make-symbols after library version changes!"
-   echo "################################################################"
-   echo ""
+   echo -e "\x1b[34m################################################################\x1b[0m"
+   echo -e "\x1b[34mDo not forget to run make-symbols after library version changes!\x1b[0m"
+   echo -e "\x1b[34m################################################################\x1b[0m"
+   echo -e ""
 fi
 
-echo "Build Test Commands:"
+echo -e "\x1b[34mBuild Test Commands:\x1b[0m"
 for DISTRIBUTION in $DISTRIBUTIONS ; do
    if [ "$DISTRIBUTION" = "unstable" -o \
         "$DISTRIBUTION" = "testing"  -o \
@@ -287,6 +324,6 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
       changesFilesPattern="${PACKAGE}_${PACKAGE_VERSION}~${DISTRIBUTION}[0-9]~ppa[0-9]_*.changes"
       dscFile=`ls ${PACKAGE}_${PACKAGE_VERSION}~${DISTRIBUTION}[0-9]~ppa[0-9].dsc | tail -n1`
    fi
-   echo "   sudo pbuilder build $dscFile && lintian -iIEv --pedantic /var/cache/pbuilder/result/$changesFilesPattern"
+   echo -e "\x1b[34m   sudo pbuilder build $dscFile && lintian -iIEv --pedantic /var/cache/pbuilder/result/$changesFilesPattern\x1b[0m"
 done
-echo ""
+echo -e ""
