Another build script update.

diff --git a/make-srpm b/make-srpm
--- a/make-srpm
+++ b/make-srpm
@@ -21,50 +21,37 @@
 
 # ---------------------------------------------------------------------------
 # USAGE:
-# ./make-rpm default            => for default distribution (F18, amd64)
-# ./make-rpm fedora-30-x86_64   => F30, amd64
-# ./make-rpm fedora-30-i386     => F30, i386
-# ...
+# ./make-rpm
 # ---------------------------------------------------------------------------
 
 
-DISTRIBUTIONS=`\
-( \
-while [ x$1 != "x" ] ; do \
-   echo $1
-   shift
-done \
-) | sort -u`
-if [ "$DISTRIBUTIONS" == "" ] ; then
-   DISTRIBUTIONS="fedora-rawhide-x86_64"
-fi
-
+# ====== Obtain package and version information =============================
 PACKAGE=`grep "^Name:" rpm/*.spec | head -n1 | sed -e "s/Name://g" -e "s/[ \t]*//g"`
 PACKAGE_VERSION=`grep "^Version:" rpm/*.spec | head -n1 | sed -e "s/Version://g" -e "s/[ \t]*//g"`
 PACKAGE_RELEASE=`grep "^Release:" rpm/*.spec | head -n1 | sed -e "s/Release://g" -e "s/[ \t]*//g"`
 
 echo -e "\x1b[34m###########################################\x1b[0m"
-echo -e "\x1b[34mPACKAGE:           $PACKAGE\x1b[0m"
-echo -e "\x1b[34mPACKAGE_VERSION:   $PACKAGE_VERSION\x1b[0m"
-echo -e "\x1b[34mPACKAGE_RELEASE:   $PACKAGE_RELEASE\x1b[0m"
+echo -e "\x1b[34mPACKAGE:           ${PACKAGE}\x1b[0m"
+echo -e "\x1b[34mPACKAGE_VERSION:   ${PACKAGE_VERSION}\x1b[0m"
+echo -e "\x1b[34mPACKAGE_RELEASE:   ${PACKAGE}_RELEASE\x1b[0m"
 echo -e "\x1b[34m###########################################\x1b[0m"
 
 # ====== Check with Debian package's version ================================
 if [ -e debian/changelog ] ; then
    DEBIAN_CHANGELOG_HEADER="`head -n1 debian/changelog`"
    # The package name, e.g. MyApplication
-   DEBIAN_PACKAGE=`echo $DEBIAN_CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
+   DEBIAN_PACKAGE=`echo ${DEBIAN_CHANGELOG_HEADER} | sed -e "s/(.*//" -e "s/ //g"`
    # The package's version, e.g. 1.2.3-1ubuntu1
-   DEBIAN_PACKAGE_VERSION=`echo $DEBIAN_CHANGELOG_HEADER | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g"`
+   DEBIAN_PACKAGE_VERSION=`echo ${DEBIAN_CHANGELOG_HEADER} | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g"`
    # The package's output version, e.g. 1.2.3-1ubuntu
-   DEBIAN_OUTPUT_VERSION=`echo $DEBIAN_PACKAGE_VERSION   | sed -e "s/\(ubuntu\)[0-9]*$/\1/"`
+   DEBIAN_OUTPUT_VERSION=`echo ${DEBIAN_PACKAGE_VERSION}   | sed -e "s/\(ubuntu\)[0-9]*$/\1/"`
    # The package's Debian version, e.g. 1.2.3-1
-   DEBIAN_VERSION=`echo $DEBIAN_OUTPUT_VERSION    | sed -e "s/ubuntu$//1"`
+   DEBIAN_VERSION=`echo ${DEBIAN_OUTPUT_VERSION}    | sed -e "s/ubuntu$//1"`
    # The package's upstream version, e.g. 1.2.3
-   DEBIAN_UPSTREAM_VERSION=`echo $DEBIAN_VERSION  | sed -e "s/-[0-9]*$//"`
+   DEBIAN_UPSTREAM_VERSION=`echo ${DEBIAN_VERSION}  | sed -e "s/-[0-9]*$//"`
 
-   if [ "$PACKAGE-$PACKAGE_VERSION" != "$DEBIAN_PACKAGE-$DEBIAN_UPSTREAM_VERSION" ] ; then
-      echo >&2 "ERROR: RPM version and Debian version do not match -> $PACKAGE-$PACKAGE_VERSION vs. $DEBIAN_PACKAGE-$DEBIAN_UPSTREAM_VERSION!"
+   if [ "${PACKAGE}-${PACKAGE_VERSION}" != "${DEBIAN_PACKAGE}-${DEBIAN_UPSTREAM_VERSION}" ] ; then
+      echo >&2 "ERROR: RPM version and Debian version do not match -> ${PACKAGE}-${PACKAGE_VERSION} vs. ${DEBIAN_PACKAGE}-${DEBIAN_UPSTREAM_VERSION}!"
       exit 1
    fi
    if [ ! -e ./debian.conf ] ; then
@@ -77,56 +64,53 @@ if [ -e rpm.conf ] ; then
    . ./rpm.conf
 fi
 
-# ====== Create upstream package ============================================
+
+# ====== Create upstream source package =====================================
 echo -e ""
-echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating upstream package ======================\x1b[0m"
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating upstream package ======================================\x1b[0m"
 echo -e ""
-if [ "$UPSTREAM_PACKAGE" = "" ] ; then
-   UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "$PACKAGE-*.gz" -printf '%f'`"
-   UPSTREAM_PACKAGE_TYPE="gz"
-   if [ ! -e "$UPSTREAM_PACKAGE" ] ; then
-      UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "$PACKAGE-*.bz2" -printf '%f'`"
-      UPSTREAM_PACKAGE_TYPE="bz2"
-   fi
-   if [ ! -e "$UPSTREAM_PACKAGE" ]; then
-      rm -f $PACKAGE-*.gz $PACKAGE"_"*.gz $PACKAGE-*.bz2 $PACKAGE"_"*.bz2
+if [ "${UPSTREAM_PACKAGE}" = "" ] ; then
+   for UPSTREAM_PACKAGE_TYPE in xz bz2 gz ; do
+      UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-*.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
+      if [ -e "${UPSTREAM_PACKAGE}" ] ; then
+         break
+      fi
+   done
+   if [ ! -e "${UPSTREAM_PACKAGE}" ]; then
+      rm -f ${PACKAGE}-*.gz ${PACKAGE}"_"*.gz ${PACKAGE}-*.bz2 ${PACKAGE}"_"*.bz2
       echo -e "\x1b[34m------ Running MAKE_DIST ... ------\x1b[0m"
       echo "\$ $MAKE_DIST"
       eval "$MAKE_DIST"
 
       echo -e "\x1b[34m------ Looking for upstream package ... ------\x1b[0m"
-      UPSTREAM_PACKAGE="`find . -maxdepth 1 -name $PACKAGE-*.gz -printf '%f'`"
-      UPSTREAM_PACKAGE_TYPE="gz"
-      if [ ! -e "$UPSTREAM_PACKAGE" ] ; then
-         UPSTREAM_PACKAGE="`find . -maxdepth 1 -name $PACKAGE-*.bz2 -printf '%f'`"
-         UPSTREAM_PACKAGE_TYPE="bz2"
-      fi
-      if [ ! -e "$UPSTREAM_PACKAGE" ] ; then
-         UPSTREAM_PACKAGE="`find . -maxdepth 1 -name $PACKAGE-*.xz -printf '%f'`"
-         UPSTREAM_PACKAGE_TYPE="xz"
-      fi
+      for UPSTREAM_PACKAGE_TYPE in xz bz2 gz ; do
+         UPSTREAM_PACKAGE="`find . -maxdepth 1 -name "${PACKAGE}-*.${UPSTREAM_PACKAGE_TYPE}" -printf '%f'`"
+         if [ -e "${UPSTREAM_PACKAGE}" ] ; then
+            break
+         fi
+      done
    fi
 fi
-if [ ! -e "$UPSTREAM_PACKAGE" ] ; then
+if [ ! -e "${UPSTREAM_PACKAGE}" ] ; then
    echo -e "\x1b[34mERROR: No upstrem package found!\x1b[0m"
    exit 1
 fi
 echo -e ""
-echo -e "\x1b[34m==> Upstream package is $UPSTREAM_PACKAGE (type is $UPSTREAM_PACKAGE_TYPE)\x1b[0m"
+echo -e "\x1b[34m==> Upstream package is ${UPSTREAM_PACKAGE} (type is ${UPSTREAM_PACKAGE_TYPE})\x1b[0m"
 echo -e ""
 
 
-# ====== Create RPMs ========================================================
+# ====== Create source RPM ==================================================
 echo -e ""
 echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating source RPM ============================\x1b[0m"
 echo -e ""
 
-# Remove old files
+# ------ Initialise RPM build directories -----------------------------------
 rpmdev-setuptree
-find $HOME/rpmbuild/SRPMS -name "$PACKAGE*.rpm" | xargs --no-run-if-empty rm -f
-find $HOME/rpmbuild/RPMS  -name "$PACKAGE*.rpm" | xargs --no-run-if-empty rm -f
+find $HOME/rpmbuild/SRPMS -name "${PACKAGE}*.rpm" | xargs --no-run-if-empty rm -f
+find $HOME/rpmbuild/RPMS  -name "${PACKAGE}*.rpm" | xargs --no-run-if-empty rm -f
 # Copy upstream sources
-cp $UPSTREAM_PACKAGE $HOME/rpmbuild/SOURCES/
+cp ${UPSTREAM_PACKAGE} $HOME/rpmbuild/SOURCES/
 # Patches
 if [ -e original ] ; then
    find original -name "*" -type f | grep -v "~$" | grep -v ".spec$" | xargs -n1 -i§ cp "§" $HOME/rpmbuild/SOURCES/
@@ -134,43 +118,12 @@ fi
 # Further patches
 find rpm -name "*" -type f | grep -v "~$" | grep -v ".spec$" | xargs -n1 -i§ cp "§" $HOME/rpmbuild/SOURCES/
 # The .spec file
-cp rpm/$PACKAGE.spec $HOME/rpmbuild/SPECS/
+cp rpm/${PACKAGE}.spec $HOME/rpmbuild/SPECS/
 
-# Create source RPM
-rpmbuild -bs rpm/$PACKAGE.spec
-PACKAGE_SRPM=`find $HOME/rpmbuild/SRPMS/ -name "$PACKAGE-*$PACKAGE_VERSION*-*.src.rpm"`
-if [ ! -e "$PACKAGE_SRPM" ] ; then
-   echo >&2 "ERROR: Cannot find SRPM $PACKAGE_SRPM!"
+# ------ Create source RPM --------------------------------------------------
+rpmbuild -bs rpm/${PACKAGE}.spec
+PACKAGE_SRPM=`find $HOME/rpmbuild/SRPMS/ -name "${PACKAGE}-*${PACKAGE_VERSION}*-*.src.rpm"`
+if [ ! -e "${PACKAGE_SRPM}" ] ; then
+   echo >&2 "ERROR: Cannot find SRPM ${PACKAGE_SRPM}!"
    exit 1
 fi
-
-# Create binary RPMs
-for DISTRIBUTION in $DISTRIBUTIONS ; do
-   echo -e ""
-   echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating binary RPM for $DISTRIBUTION ==========\x1b[0m"
-   echo -e ""
-
-   if [ ! -e "/etc/mock/$DISTRIBUTION.cfg" ] ; then
-      echo >&2 "ERROR: Cannot find /etc/mock/$DISTRIBUTION.cfg!"
-      exit 1
-   fi
-   # NOTE: DISTRIBUTION may point to another directory (e.g. "rawhide" instead of "30")!
-   distribution=`grep "config_opts..root.. =" /etc/mock/$DISTRIBUTION.cfg | sed -e "s/^.* = //g" -e "s/'//g"`
-
-   # Remove old files
-   find /var/lib/mock/$DISTRIBUTION/result -name "$PACKAGE-*.rpm" | xargs --no-run-if-empty rm -f
-
-   # Build the binary RPM
-   # NOTE: using old chroot instead of container, to allow running it inside a container!
-   mock -r $DISTRIBUTION --old-chroot --init
-   mock -r $DISTRIBUTION --old-chroot --installdeps $PACKAGE_SRPM
-   mock -r $DISTRIBUTION --old-chroot --install openssl pesign
-   mock -r $DISTRIBUTION --old-chroot --no-clean --rebuild $PACKAGE_SRPM
-
-   # Check whether files are at the right location
-   PACKAGE_RPMS=`find /var/lib/mock/$distribution/result -name "$PACKAGE-*$PACKAGE_VERSION*-*.rpm" | grep -v "$PACKAGE-*$PACKAGE_VERSION*-*.src.rpm" || true`
-   if [ "$PACKAGE_RPMS" == "" ] ; then
-      echo >&2 "ERROR: Cannot find RPMs!"
-      exit 1
-   fi
-done
