Updated build scripts.

diff --git a/ci/before-install b/ci/before-install
--- a/ci/before-install
+++ b/ci/before-install
@@ -19,14 +19,17 @@
 # Contact: dreibh@iem.uni-due.de
 
 
+CONTAINER="ubuntu-test"
+
+
 # ###### Linux ##############################################################
-if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
+if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
 
    # NOTE: Using tmpfs for pbuilder and mock!
    # The build machine therefore needs a sufficient amount of RAM!
-   sudo docker rm -f ubuntu-test || true
+   sudo docker rm -f ${CONTAINER} || true
    sudo docker run -d \
-      --name ubuntu-test \
+      --name ${CONTAINER} \
       --tmpfs /var/cache/pbuilder:rw,exec,dev,size=4g \
       --tmpfs /var/lib/mock:rw,exec,dev,size=4g \
       --cap-add=SYS_ADMIN --cap-add=NET_ADMIN \
@@ -36,13 +39,13 @@ if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
    sudo docker ps
 
 # ###### Other ##############################################################
-elif [ "$TRAVIS_OS_NAME" == "osx" ] ; then
+elif [ "${TRAVIS_OS_NAME}" == "osx" ] ; then
 
    brew update
    brew install ...
 
 # ###### Error ##############################################################
 else
-   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
+   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
    exit 1
 fi
diff --git a/ci/build b/ci/build
--- a/ci/build
+++ b/ci/build
@@ -20,33 +20,49 @@
 
 
 # ###### Linux ##############################################################
-if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
-   if [ "$TOOL" == "compile" ] ; then
-      sudo docker exec ubuntu-test bash -c "echo OPTIONS: CC=${COMPILER_C} CXX=${COMPILER_CXX}"
-      sudo docker exec ubuntu-test bash -c "env CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake ."
-      sudo docker exec ubuntu-test bash -c "env LANG=C.UTF-8 make VERBOSE=1"
+if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
+   if [ "${TOOL}" == "compile" ] ; then
 
-   elif [ "$TOOL" == "pbuilder" ] ; then
-     sudo docker exec ubuntu-test bash -c "env LANG=C.UTF-8 sed -e 's/SKIP_PACKAGE_SIGNING=0/SKIP_PACKAGE_SIGNING=1/g' -i debian.conf"
-     sudo docker exec ubuntu-test bash -c "env LANG=C.UTF-8 eatmydata ./build-deb"
+      if [ -e CMakeLists.txt ] ; then
+         sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake .
+      elif [ -e configure.ac -o -e configure.in ] ; then
+         if [ ! -e bootstrap ] ; then
+            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
+            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure
+         elif [ ! -e autogen.sh ] ; then
+            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
+         else
+            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure
+         fi
+      else
+         echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
+      fi
 
-   elif [ "$TOOL" == "mock" ] ; then
+      sudo docker exec ubuntu-test env LANG=C.UTF-8 make VERBOSE=1
+
+   elif [ "${TOOL}" == "pbuilder" ] ; then
+     sudo docker exec ubuntu-test env LANG=C.UTF-8 sed -e 's/SKIP_PACKAGE_SIGNING=0/SKIP_PACKAGE_SIGNING=1/g' -i debian.conf
+     sudo docker exec ubuntu-test env LANG=C.UTF-8 eatmydata ./build-deb
+
+   elif [ "${TOOL}" == "mock" ] ; then
       release=`sudo docker exec -t ubuntu-test bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
       arch=`sudo docker exec -t ubuntu-test env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_-+]//g"`
-      sudo docker exec ubuntu-test bash -c "env LANG=C.UTF-8  ./build-rpm fedora-${release}-${arch}"
+      sudo docker exec ubuntu-test env LANG=C.UTF-8  ./build-rpm fedora-${release}-${arch}
 
    else
-      echo >&2 "ERROR: Invalid setting of TOOL=$TOOL"
+      echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
       exit 1
    fi
 
+
 # ###### Other ##############################################################
-elif [ "$TRAVIS_OS_NAME" == "osx" ] ; then
+elif [ "${TRAVIS_OS_NAME}" == "osx" ] ; then
    cmake .
    make VERBOSE=1
 
+
 # ###### Error ##############################################################
 else
-   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
+   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
    exit 1
 fi
