Build script updates.

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -45,7 +45,13 @@ if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       fi
 
       echo "Installing ${packages} ..."
-      sudo docker exec ubuntu-test env LANG=C.UTF-8 apt-get install -y --allow-downgrades ${packages}
+      # NOTE: Older "apt-get" versions do not handle local files!
+      if ! sudo docker exec ubuntu-test env LANG=C.UTF-8 dpkg -i ${packages} ; then
+         echo "There may be some dependencies missing. Trying to install them ..."
+         sudo docker exec ubuntu-test env LANG=C.UTF-8 apt-get install -fy
+         echo "Retrying to install ${packages} ..."
+         sudo docker exec ubuntu-test env LANG=C.UTF-8 dpkg -i ${packages}
+      fi
       echo "Done!"
 
    # ====== mock environment ================================================
